FROM nginx:1.21.4

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY wait.sh /

RUN chmod +x wait.sh

CMD /wait.sh web 5000 && /wait.sh db 5432 && /wait.sh client 3000 && nginx -g "daemon off; error_log /dev/stdout info;"
