FROM python:3.9.8-slim-buster

WORKDIR /app

COPY app/requirements.txt .

RUN pip install -r requirements.txt

COPY app /app

COPY wait.sh /app

RUN chmod +x wait.sh

CMD ./wait.sh db 5432 && python3 app.py
