FROM python:3.9.8-buster

ENV PYTHONUNBUFFERED=1

COPY wait.sh /

RUN chmod +x /wait.sh

COPY app/requirements.txt /app/

RUN pip install -r /app/requirements.txt

COPY app /app

CMD sleep 20 && python3 app.py