# Following dockerizing react app on https://mherman.org/blog/dockerizing-a-react-app/
FROM node:16.10-alpine3.11

# set working directory
WORKDIR /app

ENV PATH="$PATH:/node_modules/.bin"

# install app dependencies
COPY ./client/package.json ./
COPY ./client/package-lock.json ./

RUN npm install --silent \
    && mv node_modules /

# start app
CMD ["npm", "start"]
